/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SelectSystemRouteImport } from './routes/select-system'
import { Route as SelectSessionRouteImport } from './routes/select-session'
import { Route as ScheduledRouteImport } from './routes/scheduled'
import { Route as RestoreRouteImport } from './routes/restore'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProcedureRouteImport } from './routes/procedure'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcedureIndexRouteImport } from './routes/procedure.index'
import { Route as ProcedureSeedEvaluationsRouteImport } from './routes/procedure.seed-evaluations'
import { Route as ProcedureResetEvaluationsRouteImport } from './routes/procedure.reset-evaluations'
import { Route as ProcedureIdRouteImport } from './routes/procedure.$id'
import { Route as AdminNucleusNucleoRouteImport } from './routes/admin-nucleus.$nucleo'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectSystemRoute = SelectSystemRouteImport.update({
  id: '/select-system',
  path: '/select-system',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectSessionRoute = SelectSessionRouteImport.update({
  id: '/select-session',
  path: '/select-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreRoute = RestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedureRoute = ProcedureRouteImport.update({
  id: '/procedure',
  path: '/procedure',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedureIndexRoute = ProcedureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcedureRoute,
} as any)
const ProcedureSeedEvaluationsRoute =
  ProcedureSeedEvaluationsRouteImport.update({
    id: '/seed-evaluations',
    path: '/seed-evaluations',
    getParentRoute: () => ProcedureRoute,
  } as any)
const ProcedureResetEvaluationsRoute =
  ProcedureResetEvaluationsRouteImport.update({
    id: '/reset-evaluations',
    path: '/reset-evaluations',
    getParentRoute: () => ProcedureRoute,
  } as any)
const ProcedureIdRoute = ProcedureIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProcedureRoute,
} as any)
const AdminNucleusNucleoRoute = AdminNucleusNucleoRouteImport.update({
  id: '/admin-nucleus/$nucleo',
  path: '/admin-nucleus/$nucleo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/menu': typeof MenuRoute
  '/procedure': typeof ProcedureRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/restore': typeof RestoreRoute
  '/scheduled': typeof ScheduledRoute
  '/select-session': typeof SelectSessionRoute
  '/select-system': typeof SelectSystemRoute
  '/system': typeof SystemRoute
  '/admin-nucleus/$nucleo': typeof AdminNucleusNucleoRoute
  '/procedure/$id': typeof ProcedureIdRoute
  '/procedure/reset-evaluations': typeof ProcedureResetEvaluationsRoute
  '/procedure/seed-evaluations': typeof ProcedureSeedEvaluationsRoute
  '/procedure/': typeof ProcedureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/menu': typeof MenuRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/restore': typeof RestoreRoute
  '/scheduled': typeof ScheduledRoute
  '/select-session': typeof SelectSessionRoute
  '/select-system': typeof SelectSystemRoute
  '/system': typeof SystemRoute
  '/admin-nucleus/$nucleo': typeof AdminNucleusNucleoRoute
  '/procedure/$id': typeof ProcedureIdRoute
  '/procedure/reset-evaluations': typeof ProcedureResetEvaluationsRoute
  '/procedure/seed-evaluations': typeof ProcedureSeedEvaluationsRoute
  '/procedure': typeof ProcedureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/menu': typeof MenuRoute
  '/procedure': typeof ProcedureRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/restore': typeof RestoreRoute
  '/scheduled': typeof ScheduledRoute
  '/select-session': typeof SelectSessionRoute
  '/select-system': typeof SelectSystemRoute
  '/system': typeof SystemRoute
  '/admin-nucleus/$nucleo': typeof AdminNucleusNucleoRoute
  '/procedure/$id': typeof ProcedureIdRoute
  '/procedure/reset-evaluations': typeof ProcedureResetEvaluationsRoute
  '/procedure/seed-evaluations': typeof ProcedureSeedEvaluationsRoute
  '/procedure/': typeof ProcedureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/history'
    | '/menu'
    | '/procedure'
    | '/profile'
    | '/register'
    | '/restore'
    | '/scheduled'
    | '/select-session'
    | '/select-system'
    | '/system'
    | '/admin-nucleus/$nucleo'
    | '/procedure/$id'
    | '/procedure/reset-evaluations'
    | '/procedure/seed-evaluations'
    | '/procedure/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/history'
    | '/menu'
    | '/profile'
    | '/register'
    | '/restore'
    | '/scheduled'
    | '/select-session'
    | '/select-system'
    | '/system'
    | '/admin-nucleus/$nucleo'
    | '/procedure/$id'
    | '/procedure/reset-evaluations'
    | '/procedure/seed-evaluations'
    | '/procedure'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/history'
    | '/menu'
    | '/procedure'
    | '/profile'
    | '/register'
    | '/restore'
    | '/scheduled'
    | '/select-session'
    | '/select-system'
    | '/system'
    | '/admin-nucleus/$nucleo'
    | '/procedure/$id'
    | '/procedure/reset-evaluations'
    | '/procedure/seed-evaluations'
    | '/procedure/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  MenuRoute: typeof MenuRoute
  ProcedureRoute: typeof ProcedureRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RestoreRoute: typeof RestoreRoute
  ScheduledRoute: typeof ScheduledRoute
  SelectSessionRoute: typeof SelectSessionRoute
  SelectSystemRoute: typeof SelectSystemRoute
  SystemRoute: typeof SystemRoute
  AdminNucleusNucleoRoute: typeof AdminNucleusNucleoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-system': {
      id: '/select-system'
      path: '/select-system'
      fullPath: '/select-system'
      preLoaderRoute: typeof SelectSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-session': {
      id: '/select-session'
      path: '/select-session'
      fullPath: '/select-session'
      preLoaderRoute: typeof SelectSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore': {
      id: '/restore'
      path: '/restore'
      fullPath: '/restore'
      preLoaderRoute: typeof RestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedure': {
      id: '/procedure'
      path: '/procedure'
      fullPath: '/procedure'
      preLoaderRoute: typeof ProcedureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedure/': {
      id: '/procedure/'
      path: '/'
      fullPath: '/procedure/'
      preLoaderRoute: typeof ProcedureIndexRouteImport
      parentRoute: typeof ProcedureRoute
    }
    '/procedure/seed-evaluations': {
      id: '/procedure/seed-evaluations'
      path: '/seed-evaluations'
      fullPath: '/procedure/seed-evaluations'
      preLoaderRoute: typeof ProcedureSeedEvaluationsRouteImport
      parentRoute: typeof ProcedureRoute
    }
    '/procedure/reset-evaluations': {
      id: '/procedure/reset-evaluations'
      path: '/reset-evaluations'
      fullPath: '/procedure/reset-evaluations'
      preLoaderRoute: typeof ProcedureResetEvaluationsRouteImport
      parentRoute: typeof ProcedureRoute
    }
    '/procedure/$id': {
      id: '/procedure/$id'
      path: '/$id'
      fullPath: '/procedure/$id'
      preLoaderRoute: typeof ProcedureIdRouteImport
      parentRoute: typeof ProcedureRoute
    }
    '/admin-nucleus/$nucleo': {
      id: '/admin-nucleus/$nucleo'
      path: '/admin-nucleus/$nucleo'
      fullPath: '/admin-nucleus/$nucleo'
      preLoaderRoute: typeof AdminNucleusNucleoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProcedureRouteChildren {
  ProcedureIdRoute: typeof ProcedureIdRoute
  ProcedureResetEvaluationsRoute: typeof ProcedureResetEvaluationsRoute
  ProcedureSeedEvaluationsRoute: typeof ProcedureSeedEvaluationsRoute
  ProcedureIndexRoute: typeof ProcedureIndexRoute
}

const ProcedureRouteChildren: ProcedureRouteChildren = {
  ProcedureIdRoute: ProcedureIdRoute,
  ProcedureResetEvaluationsRoute: ProcedureResetEvaluationsRoute,
  ProcedureSeedEvaluationsRoute: ProcedureSeedEvaluationsRoute,
  ProcedureIndexRoute: ProcedureIndexRoute,
}

const ProcedureRouteWithChildren = ProcedureRoute._addFileChildren(
  ProcedureRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  MenuRoute: MenuRoute,
  ProcedureRoute: ProcedureRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RestoreRoute: RestoreRoute,
  ScheduledRoute: ScheduledRoute,
  SelectSessionRoute: SelectSessionRoute,
  SelectSystemRoute: SelectSystemRoute,
  SystemRoute: SystemRoute,
  AdminNucleusNucleoRoute: AdminNucleusNucleoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
